name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gh_action_lint:
    uses: masutaka/actions/.github/workflows/gh_action_lint.yml@main
    permissions:
      contents: read
  codeql:
    uses: masutaka/actions/.github/workflows/codeql.yml@main
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rake spec
  pushover:
    name: pushover if failure
    if: github.ref_name == github.event.repository.default_branch && failure()
    needs: [gh_action_lint, codeql, rspec]
    uses: masutaka/actions/.github/workflows/pushover.yml@main
    permissions: {}
    secrets:
      PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
